apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  storageClassName: "minio-storageclass"
  local:
    path: /mnt/disks/ssd2
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: kubeflow
    name: minio-pv-claim
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/minio
          operator: In
          values:
          - slave-90
          - slave-91
          - slave-46
          - master
